# Theme
# theme: beautiful-jekyll-theme
remote_theme: daattali/beautiful-jekyll

# Website name at top left
title: "Joseph Nagel"

# Author name in the footer
author: "Joseph Nagel"

# Avatar picture at the top
avatar: "/assets/images/Small.png"

# Social media links at the bottom
social-network-links:
  email: "JosephBNagel@gmail.com"
  github: joseph-nagel

